//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationUser
    {
        public int ApplicationUserId { get; set; }
        public Nullable<int> UserIdentityKey { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string MemberCode { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string Image { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblUserTypeMaster tblUserTypeMaster { get; set; }
    }
}
